# Generated by Django 5.2.3 on 2026-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0006_remove_book_review_forms_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review_forms',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
