# Generated by Django 5.2.3 on 2026-09-07 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0007_book_date_added_alter_book_review_forms_book_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraicredit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
