# Generated by Django 5.2.3 on 2026-01-13 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0007_book_review_forms_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review_forms',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
