# Generated by Django 5.2.3 on 2026-09-07 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0008_alter_useraicredit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
