# Generated by Django 5.2.3 on 2026-09-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0010_alter_book_date_added_alter_userprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book_review_forms',
            name='book_review',
            field=models.TextField(max_length=500),
        ),
    ]
