# Generated by Django 5.2.3 on 2026-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0011_alter_book_title_alter_book_review_forms_book_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WELCOME_EMAIL', 'Welcome Email')], max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
